steps:
  - name: 'python'
    args: ['pip3','install', '-r', 'requirements.txt', '--user']
  # This installs your requirements and `--user` makes them persist between steps
  
  # - name: 'python'
  #   args: ['python3','pytest', 'functions/folder_a/test/'] #run all tests in the tests folder
  
  # Create a task for each function as shown here: https://cloud.google.com/functions/docs/bestpractices/testing#continuous_testing_and_deployment
  - name: 'gcr.io/cloud-builders/gcloud']
      id: 'deployMyFunction'
    args: ['functions', 'deploy', 'my-function', '--source' , 'functions/folder_a/main.py', '--runtime' , 'python37' ,'--trigger-http']
  
  # # Option B: Write some python that iterates and deploys each function, although I can't seem to find the Cloud Functions in the python SDK SPI.
  # - name: 'python'
  #   args: ['python3','deploy.py']
  #   env:
  #   - 'PROJECT_ID=${_PROJECT_ID}'
  